import {useState} from 'react';
import {Crown,Compass,Bookmark,Map,ArrowUpRight,Plus,Minus,Maximize,ArrowUp,ArrowDown,ArrowLeft,ArrowRight,ChevronDown,Globe2,CircleHelp,Navigation,X,MapPin,Loader2} from 'lucide-react';
import {ContinentMap} from './ContinentMap';
import {capturePointer} from '../lib/pointer';
import {BuildingPreview} from './BuildingPanels';
export const GameHUD=({worlds,places,player,position,activeWorld,settings,joystick,home,setPanel,scene,chunkCount,building,plot,checkingLand,enterBuilding,createTerritory,clearSelection,savePlace,openWorld})=>{
  const [collapsed,setCollapsed]=useState(false),[pressed,setPressed]=useState('');
  const directions=[[ArrowUp,'up',0,-1],[ArrowLeft,'left',-1,0],[ArrowDown,'down',0,1],[ArrowRight,'right',1,0]];
  return <>
    <section className={`realm-card hud-surface ${collapsed?'collapsed':''}`} data-testid="realm-info"><div className="realm-eyebrow"><span><Globe2 size={13}/>{activeWorld?'COMMUNITY TERRITORY':'THE SHARED CONTINENT'}</span><button data-testid="toggle-realm-info" aria-label="Toggle continent information" onClick={()=>setCollapsed(!collapsed)}><ChevronDown size={15}/></button></div>
      {!collapsed&&<><h2 data-testid="realm-name">{activeWorld?.name||'Small pixels.\nA world of places.'}</h2><p>{activeWorld?`$${activeWorld.symbol} · A community with a place of its own.`:'A strange little civilization. An enormous place to explore.'}</p><div className="map-summary-stats"><span><strong data-testid="world-count">{worlds.length}</strong> territories</span><span><strong data-testid="saved-place-count">{places.length}</strong> places saved</span></div><button className="realm-action" data-testid="realm-explore-button" onClick={()=>activeWorld?openWorld(activeWorld):setPanel('explore')}>Discover communities<ArrowUpRight size={16}/></button></>}
    </section>
    {building&&<div className="building-prompt hud-surface" data-testid="building-prompt"><BuildingPreview kind={building.kind} scene={scene} small/><div className="building-prompt-copy"><small>{building.category||'COMMUNITY BUILDING'}</small><strong data-testid="selected-building-name">{building.name}</strong><span>{Math.round(building.x).toLocaleString()} : {Math.round(building.y).toLocaleString()}</span></div><button className="save-building" data-testid="save-building-button" title="Save this place" aria-label="Save this place" onClick={()=>savePlace(building)}><Bookmark size={17}/></button><button className="enter-building" data-testid="enter-building-button" onClick={enterBuilding}>Enter<ArrowRight size={15}/></button><button className="dismiss-prompt" data-testid="dismiss-building-prompt" aria-label="Close building prompt" onClick={clearSelection}><X size={13}/></button></div>}
    {!building&&(plot||checkingLand)&&<div className="land-prompt hud-surface" data-testid="land-prompt"><MapPin size={23}/><div><strong data-testid="land-status">{checkingLand?'Checking land…':plot.available?'Unclaimed land':'Reserved landscape'}</strong><p data-testid="land-details">{checkingLand?'':plot.available?`${plot.biome} · ${plot.x.toLocaleString()}, ${plot.y.toLocaleString()}`:plot.reason}</p></div>{checkingLand?<Loader2 className="spin" size={18}/>:plot.available&&<button className="enter-building" data-testid="create-on-land-button" onClick={createTerritory}><Plus size={15}/>Create territory</button>}<button className="dismiss-prompt" data-testid="dismiss-land-prompt" aria-label="Close land selection" onClick={clearSelection}><X size={13}/></button></div>}
    <div className="action-dock hud-surface" data-testid="action-bar">{[[Crown,'home','Capital',home],[Compass,'explore','Explore',()=>setPanel('explore')],[Bookmark,'collection','Saved places',()=>setPanel('collection')],[Map,'map','World map',()=>setPanel('map')]].map(([Icon,id,label,action])=><button key={id} data-testid={`dock-${id}`} title={label} aria-label={label} onClick={action}><Icon size={21}/><span>{label}</span></button>)}</div>
    <div className="world-controls"><button data-testid="zoom-in" aria-label="Zoom in" title="Zoom in" onClick={()=>scene.current?.zoom(.1)}><Plus size={18}/></button><button data-testid="zoom-out" aria-label="Zoom out" title="Zoom out" onClick={()=>scene.current?.zoom(-.1)}><Minus size={18}/></button><button data-testid="recenter-map" aria-label="Reset zoom" title="Reset zoom" onClick={()=>scene.current?.resizeCamera()}><Maximize size={16}/></button></div>
    {settings.map&&<button className="minimap hud-surface" data-testid="minimap-open" aria-label="Open continent map" onClick={()=>setPanel('map')}><ContinentMap worlds={worlds} position={position} discovered={player.discovered} mini/><span className="minimap-caption"><Navigation size={12}/>THE CONTINENT<Maximize size={12}/></span></button>}
    <div className="mobile-pad" data-testid="mobile-controls">{directions.map(([Icon,name,x,y])=><button key={name} className={`pad-${name} ${pressed===name?'pressed':''}`} data-testid={`move-${name}`} aria-label={`Pan ${name}`} onPointerDown={e=>{capturePointer(e);joystick.current={x,y};setPressed(name);}} onPointerUp={()=>{joystick.current={x:0,y:0};setPressed('');}} onPointerCancel={()=>{joystick.current={x:0,y:0};setPressed('');}} onLostPointerCapture={()=>{joystick.current={x:0,y:0};setPressed('');}}><Icon size={21}/></button>)}</div>
    <div className="world-footer"><span data-testid="world-network"><i/> SOLANA MAINNET <span className="footer-divider">/</span><Globe2 size={11}/> ONE SHARED WORLD</span><button data-testid="open-controls-help" onClick={()=>setPanel('help')}><CircleHelp size={12}/>Controls</button><span className="coordinate" data-testid="player-coordinates">{Math.round(position.x).toLocaleString()} : {Math.round(position.y).toLocaleString()}<span className="chunk-status" data-testid="active-chunks"> · {chunkCount} chunks</span></span></div>
  </>;
};