import {useEffect,useState} from 'react';
import {ArrowUpRight,Bookmark,Check,Compass,Globe2,Keyboard,LogOut,MapPin,MousePointer2,ShieldCheck,Trash2,Wallet} from 'lucide-react';
import {Panel} from './Panel';
import {TokenLogo} from './WorldPanels';
import {ContinentMap} from './ContinentMap';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Switch} from './ui/switch';
import {toast} from './ui/sonner';
import {api,errorMessage} from '../lib/api';
export const PlayerPanels=({panel,setPanel,player,setPlayer,worlds,places,refreshPlaces,settings,setSettings,connectWallet,busy,home,position,setSelected,visitPlace})=>{
  const [name,setName]=useState(player.name),[saving,setSaving]=useState(false);const close=()=>setPanel(null);
  useEffect(()=>{setName(player.name);},[player.name]);
  const saveProfile=async e=>{e.preventDefault();setSaving(true);try{setPlayer((await api.patch('/players/me',{name})).data);close();toast.success('Profile updated.');}catch(e){toast.error(errorMessage(e));}finally{setSaving(false);}};
  const disconnect=async()=>{try{setPlayer((await api.post('/auth/disconnect')).data);await window.phantom?.solana?.disconnect();toast.success('Wallet disconnected.');}catch(e){toast.error(errorMessage(e));}};
  const remove=async key=>{try{await api.delete(`/places/${encodeURIComponent(key)}`);await refreshPlaces();}catch(e){toast.error(errorMessage(e));}};
  return <>
    <Panel open={panel==='profile'} onClose={close} title="Your place in Kingcom." subtitle="A simple account for your communities and saved places." id="profile"><form onSubmit={saveProfile} className="profile-form"><label htmlFor="visitor-name">Display name</label><Input id="visitor-name" data-testid="player-name-input" value={name} minLength={2} maxLength={20} required onChange={e=>setName(e.target.value)}/><Button className="full-button" type="submit" data-testid="save-profile-button" disabled={saving}>Save profile<Check size={16}/></Button></form><div className="profile-wallet"><button data-testid="profile-connect-wallet" onClick={player.wallet?()=>setPanel('wallet'):connectWallet}><Wallet size={15}/>{player.wallet?'View connected wallet':'Connect Phantom'}<ArrowUpRight size={15}/></button></div></Panel>
    <Panel open={panel==='settings'} onClose={close} title="A world your way." subtitle="Keep your view as simple as you like." id="settings"><div className="settings-options">{[['map','Show minimap','The surrounding continent at a glance.'],['labels','Territory labels','Community names on the world map.']].map(([id,title,description])=><label key={id}><span><strong>{title}</strong><small>{description}</small></span><Switch data-testid={`setting-${id}`} checked={settings[id]} onCheckedChange={value=>setSettings(s=>({...s,[id]:value}))}/></label>)}</div><div className="settings-bottom"><Globe2 size={15}/>Kingcom · Solana mainnet</div></Panel>
    <Panel open={panel==='collection'} onClose={close} title="Collection Hall" subtitle={`${places.length} saved places. A personal atlas of the internet.`} id="collection"><div className="saved-places-list">{places.map(p=><div key={p.place_key} data-testid={`saved-place-${p.place_key}`}><button data-testid={`visit-place-${p.place_key}`} onClick={()=>visitPlace(p)}><MapPin size={18}/><span><strong>{p.name}</strong><small>{p.x.toLocaleString()}, {p.y.toLocaleString()}</small></span><ArrowUpRight size={15}/></button><button data-testid={`remove-place-${p.place_key}`} title="Remove saved place" aria-label={`Remove ${p.name}`} onClick={()=>remove(p.place_key)}><Trash2 size={14}/></button></div>)}</div>{!places.length&&<div className="empty-state" data-testid="saved-places-empty"><Bookmark size={33}/><h3>A world worth remembering.</h3><p>Your saved buildings and landmarks will be here.</p></div>}</Panel>
    <Panel open={panel==='leaderboard'} onClose={close} title="Community Hall" subtitle="Communities growing their corner of the continent." id="leaderboard"><div className="leaderboard-labels"><span>COMMUNITY</span><span>PROGRESS</span></div><div className="leaderboard-list">{[...worlds].sort((a,b)=>b.points-a.points).map((w,i)=><button className="leaderboard-row" key={w.id} data-testid={`leaderboard-rank-${i+1}`} onClick={()=>{setSelected(w);setPanel('world');}}><span className={`rank rank-${i}`}>{i+1}</span><TokenLogo world={w}/><span><strong>{w.name}</strong><small>{w.citizens} citizens</small></span><strong>{w.points}<small> points</small></strong></button>)}</div></Panel>
    <Panel open={panel==='map'} onClose={close} wide title="The world goes on." subtitle="65,536 × 65,536 coordinates. One persistent continent." id="map"><ContinentMap worlds={worlds} position={position} discovered={player.discovered} onTerritory={w=>{setSelected(w);setPanel('world');}} onCapital={home}/><div className="map-legend" data-testid="map-legend"><span><i className="legend-capital"/>Kingcom</span><span><i className="legend-community"/>Community territory</span><span><i className="legend-player"/>Current view</span></div><div className="map-world-links">{worlds.map(w=><button data-testid={`map-list-${w.id}`} key={w.id} onClick={()=>{setSelected(w);setPanel('world');}}><i className={`region-dot region-${w.region%4}`}/>{w.name}<ArrowUpRight size={13}/></button>)}</div></Panel>
    <Panel open={panel==='wallet'} onClose={close} title={player.wallet?'Your community passport.':'Meme Bank'} subtitle="Your wallet connects you to holder-only community spaces." id="wallet"><div className="wallet-explainer"><Wallet size={35}/>{player.wallet?<><h3>Phantom connected</h3><p className="wallet-address" data-testid="connected-wallet-address">{player.wallet}</p><span><ShieldCheck size={16}/>Wallet ownership verified on Solana</span></>:<><h3>Connect with Phantom</h3><p>On desktop, use the Phantom browser extension. On mobile, open Kingcom in the Phantom app's browser.</p><span><ShieldCheck size={16}/>A signature only. No payment or transaction.</span></>}</div>{player.wallet?<Button className="full-button" variant="outline" data-testid="disconnect-wallet-button" onClick={disconnect}><LogOut size={16}/>Disconnect wallet</Button>:<Button data-testid="retry-phantom-connect" className="full-button" onClick={connectWallet} disabled={busy}>Connect Phantom<ArrowUpRight size={16}/></Button>}</Panel>
    <Panel open={panel==='help'} onClose={close} title="Explore at your own pace." subtitle="A continent of buildings, communities, and places to discover." id="help"><div className="controls-list"><span><MousePointer2 size={22}/><strong>Explore the map</strong><span>Drag or swipe to move the camera</span></span><span><Keyboard size={22}/><strong>Pan with your keyboard</strong><span>WASD or arrow keys · Shift for faster movement</span></span><span><Compass size={22}/><strong>Discover a place</strong><span>Click a building, then Enter</span></span><span><MapPin size={22}/><strong>Create a territory</strong><span>Click unclaimed land beyond the cities</span></span></div></Panel>
  </>;
};